name: data_source
description: A generic interface for managing todos.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
dependencies:
  build_runner: ^2.4.6
  realm_dart: ^1.5.0
  equatable: ^2.0.5
  json_serializable: ^6.7.1
  meta: ^1.10.0
  isar: ^3.1.0+1
  isar_generator: ^3.1.0+1
