name: todos_api_dart_project
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  data_repository:
    path: packages/data_repository
  data_source:
    path: packages/data_source
  http: ^1.1.0
  realm_dart: ^1.5.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  isar: ^3.1.0+1
  isar_generator: ^3.1.0+1
