name: data_repository
description: An in-memory implementation of the TodosDataSource interface.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  data_source:
    path: ../data_source
  uuid: ^3.0.6

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  realm_dart: ^1.5.0
  very_good_analysis: ^5.1.0
  isar: ^3.1.0+1
  isar_generator: ^3.1.0+1
